[package]
name = "hello_cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
serde = "1"
serde_json = "1"
tokio = { version = "1", features = ["full"] }
actix-files = "0.6.5"